# Generated by Django 4.0.1 on 2022-01-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoldHouse',
            fields=[
                ('tx_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('price_paid', models.IntegerField()),
                ('tx_date', models.DateTimeField()),
                ('post_code', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=50)),
                ('new_build', models.BooleanField()),
                ('estate_type', models.CharField(max_length=50)),
                ('paon', models.CharField(max_length=50)),
                ('saon', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('record_status', models.CharField(max_length=50)),
            ],
        ),
    ]
