# Generated by Django 4.0.1 on 2022-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0002_alter_soldhouse_county_alter_soldhouse_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldhouse',
            name='tx_date',
            field=models.DateField(verbose_name='Transaction Date'),
        ),
    ]
